apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  volumes: 
  - name: secret-vol
    secret:
      name: db-credentials
  containers:
  - image: nginx
    name: backend
    volumeMounts: 
    - name: secret-vol
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
