apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  volumes:
  - name: vol-ref
    emptyDir: {}
  initContainers:
  - name: configurer
    image: busybox
    command:
    - wget
    - "-O"
    - "/usr/shared/app/config.json"
    - "https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/07-creating-init-container/app/config/config.json"
    volumeMounts:
    - name: vol-ref
      mountPath: /usr/shared/app
  containers:
  - image: bmuschko/nodejs-read-config:1.0.0
    name: web
    volumeMounts:
    - name: vol-ref
      mountPath: /usr/shared/app
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
