apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-depl
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-depl
    spec:
      containers:
      - image: nginx
        name: nginx
        envFrom:
        - configMapRef:
            name: db-config
        resources: {}
status: {}
