apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend2
  name: backend2
spec:
  containers:
  - image: nginx
    name: backend
    resources: {}
    envFrom:
    - configMapRef:
        name: db-config2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
