apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test2
  name: test2
spec:
  containers:
  - command:
    - wget
    - -O
    - test.json
    - https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/07-creating-init-container/app/config/config.json
    image: busybox
    name: test2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
