apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: myjob
spec:
  activeDeadlineSeconds: 20
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo HELLO; sleep 30; echo WORLD
        image: busybox
        name: myjob
        resources: {}
      restartPolicy: Never
status: {}
