apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv
  labels: 
    type: local
spec: 
  storageClassName: shared
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Mi
  hostPath: 
    path: /data/config
