apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  selector:
    matchLabels:
      type: local
  storageClassName: shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
