apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: myrq2
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    pods: "1"
    limits.cpu: "1"
    limits.memory: 1Gi
status: {}
