apiVersion: v1
kind: PersistentVolume
metadata: 
  name: myvolume
spec: 
  storageClassName: normal
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: "/etc/foo"
