apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
      - name: pv-storage
        mountPath: "/etc/foo"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
