apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend6
  name: backend6
  selfLink: /api/v1/namespaces/default/pods/backend5
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 10; echo `date` >> test.txt;
    image: busybox
    imagePullPolicy: Always
    name: backend5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-w48zx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-w48zx
    secret:
      defaultMode: 420
      secretName: default-token-w48zx
status:
  phase: Pending
  qosClass: BestEffort
