apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
spec:
  containers:
  - image: nginx
    name: test-pod
    resources:
      requests: 
        cpu: "200m"
        memory: "200m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
